pipeline {
  agent any

  stages {
   stage('build') {
      steps {
          sh 'echo "heello" > saneeep '
           }
}

  stage('docker step') {
      steps {
          sh 'sudo docker pull centos'
           }

}
}
}
